CREATE USER edwin WITH PASSWORD 'acid';
CREATE DATABASE edwin;
GRANT ALL PRIVILEGES ON DATABASE edwin TO edwin;
\c edwin;
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    wallet INTEGER,
    permission BOOLEAN NOT NULL DEFAULT TRUE
);
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO edwin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO edwin;

