CREATE USER edwin WITH PASSWORD 'acid';
CREATE DATABASE edwin;
GRANT ALL PRIVILEGES ON DATABASE edwin TO edwin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO edwin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO edwin;

